name: Convert MD to HTML
on:
  push:
    branches: ['main']
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - run: ls -al
    - run: npm i markdown-to-html-cli -g
    - run: markdown-to-html --output index.html
    - run: markdown-to-html --source README.md --output index.html
