name: Convert MD to HTML
on:
  push:
    branches: ['main']
jobs:
  Job:
    runs-on: windows-latest
    steps:
    - name: Converts markdown text to HTML
      uses: jaywcjlove/markdown-to-html-cli@v4.1.0
      with:
        source: README.md
        output: index.html
        github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
